style: update theme to match MITxOnline Site
mitodl/mitxonline-zendesk-theme pull request #4
Opened 2021-12-14 12:04 UTC by arslanashraf7

## Related Ticket:
#3 

## What this PR Does?
- Update the zendesk theme to match the MITxOnline site
- Adds Contact Us block
- Adds header design changes
- Updates the site logo
- Updates the header

2021-12-15 14:18 UTC, arslanashraf7 commented
@briangrossman Could you take a look at the screenshots attached in the PR description and let me know if they look good. Also, You can check this theme in the test instance (https://mitxonline-test-theme.zendesk.com/hc/en-us).

2021-12-16 01:55 UTC, briangrossman commented
@arslanashraf7 This looks great. Nice work. Thanks for setting up the demo site, too!

It looks like you took care of everything. 👍

2021-12-16 15:14 UTC, arslanashraf7 commented
@umarmughal824 On the note of reviewing the PR I just wanted to add that if you could review this PR you won't need to review the other one related to footer (#3 ) since it is already rebased on that & includes all the changes of the footer as well.

2021-12-17 10:02 UTC, umarmughal824 requested changes
Few concerns

- it seems very inconsistent that at some points we are using hexadecimal color and others using variables defined against hexadecimal values. We should defined variable against each hexadecimal values
- some classes are using #000 as a color but we have defined a variable against it already `mit-header-link-color` that should be used
- in some media queries 100% for screen sizes is being used even though we have define a variable against it in variables `max-width-container` that should be used
- even though we could define all screen sizes here in variable against 1024, 768 and 576 and used these variable. I could see some variables are already defined so better to use them
- it's better to use variables for all screen sizes its also inconsistent at some places you are using variables and and others using hard coded values so better to use variables

2021-12-17 10:02 UTC, umarmughal824 commented on templates/footer.hbs
> +          <img src="{{settings.mit_footer_logo}}" width="78" height="41" alt="MIT" loading="lazy"/>
please define the styling in `.scss` file. My concern here is for width and height

2021-12-20 10:55 UTC, arslanashraf7 commented on style.css
> +@media (max-width: 576px) {
Updated & Replaced with mobile.

2021-12-20 10:55 UTC, arslanashraf7 commented on style.css
> +    color: #000000;
Updated

2021-12-20 10:55 UTC, arslanashraf7 commented on templates/footer.hbs
> +          <img src="{{settings.mit_footer_logo}}" width="78" height="41" alt="MIT" loading="lazy"/>
Updated

2021-12-20 10:55 UTC, arslanashraf7 commented
@umarmughal824 I have addressed your feedback and it's ready for review again.

2021-12-21 08:28 UTC, umarmughal824 requested changes

2021-12-21 08:28 UTC, umarmughal824 commented on styles/_header.scss
> +  padding: 5px 2% 5px 2%;
This should have been written
`padding: 5px 2%`

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 100%) {
At least in all media queries we could use $max-width-container variable against 100%

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  padding: 5px 2% 5px 2%;
Use `5px 2%`

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 100%) {
Same concern

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  color: #000000;
Better to define a variable against it and use that everywhere in that file

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  color: #000000;
Same concern

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  color: #000000;
Same

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  padding: 0 32px 0 32px !important;
`padding: 0 32px`

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  background: #f5f5f5;
Don't we have any variable against it?

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  background: #c2c2c2;
Same

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (max-width: 768px) {
Better to use tablet variable here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (max-width: 768px) {
Same

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  background: #006b9c;
Same

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Same

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Same

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Here too

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
>  @media (min-width: 768px) {
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 768px) {
Here and where ever you find that in the same file

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +@media (min-width: 1024px) {
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  background: #ae1f34;
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +    color: #000000;
Here

2021-12-21 08:28 UTC, umarmughal824 commented on style.css
> +  background-color: #ae1f34;
Here

2021-12-21 08:50 UTC, umarmughal824 approved these changes
👍 , Just a few minor concerns feel free to merge after that.

Make sure you have tested it out after deploying too

2021-12-21 09:41 UTC, arslanashraf7 commented
Feedback addressed & the final changes have also been deployed at https://mitxonline-test-theme.zendesk.com/hc/en-us/. I'm going to merge this PR.

2021-12-21 09:41 UTC, merged